[workspace]
members = [
    "./enalang",
    "./enalang_compiler",
    "./enalang_vm",
    "./enalang_checker",
    "./enalang_cgen",
    "./enalang_optimizer",
    "./enalang_ir",
    "./enalang_docgen"
]
